
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('沒有選擇匹配的產品.') ?></p>
<?php else: ?>
     <?php echo $this->getToolbarHtml() ?>
  <div id="tab-grid" class="diamond-grid-list">
         <div id="scrollcontent">
		<div class="search-content">
		<ul class="search-list-wrap clearfix">
      <?php // Grid Mode  ?>
                    <?php $_collectionSize = $_productCollection->count() ?>
                    <?php $_columnCount = 4; //$this->getColumnCount(); ?>
                    <?php $i = 0;
                    foreach ($_productCollection as $_product):
                        ?>
			<li>
			<div class="slider-small search-item">
			<figure>
			
			<a
			href="<?php echo $_product->getProductUrl()?>"
			title="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>"
			class="product-image" style="height: 100%; width: 100%;"
			id="product_<?php echo $_product->getId() ?>">

			<img alt="diamond" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(141); ?>" />
				
			</a>
			</figure>
			<h3><a href=""
			 title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
			 <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
			 </a>
			 </h3>
			<span class="diamond-properties"> 
			<span>質材:<?php echo $_product->getResource()->getAttribute('ring_metal')->getFrontend()->getValue($_product)?></span> 
	<div style="min-height:43px">
		 <?php echo $this->getLayout()->createBlock('review/helper')->getSummaryHtml($_product, false, true)?>
     </div>		
		<span class="norm"><?php echo Mage::helper("core")->currency($_product->getFinalPrice()) ?>
			</span>

               </div>
			</li>
			<?php endforeach ?>
			</ul>
			</div>
			</div>
			</div>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>




<?php endif; ?>
