<?php $dids =$this->getd();

?>

<?php /* @var $this Ikantam_Diamonds_Block_Product_Compare_List */ ?>
<?php 
		$_items =Mage::getmodel("catalog/product")->getcollection()
		->addattributetoselect("*")
			->addfieldtofilter("entity_id",array("in"=>$dids));
		
?>
<div class="compaire-diamond-overlay " style="display: block;">
			<div class="outer-div">
<div class="compaire-diamond">
			<a href="javascript:void(0);" class="close-popup close-compaire"><img src="http://mycarthk.com/magento/skin/frontend/mycart/peakao/images/popup-close.png" alt="close"></a>
				<div id="compare-list" class="category-products">      
<?php if ($_items->getSize() == 0): /*$this->getItems()*/?>
    <p class="note-msg"><?php echo $this->__('沒有符合條件的鑽石.') ?></p>
<?php else: ?>
    <?php $_helper = $this->helper('diamonds'); ?>
    <?php //$_items = $this->getItems(); ?>
						<ul class="compaire-list">
							<li class="first-list-pop">
								<div class="top-pop-head">
									<h2>調整鑽石</h2>
								</div>
					
								<ul class="inner-pop-list first-inner">
									<li>
										名稱
									</li>
									<li>
										價錢
									<li>
										形狀
									</li>
									<li>
										克拉重量
									</li>
									<li>
										切割
									</li>
									<li>
										成色
									</li>
									<li>
										淨度
									</li>
									<li>
										拋光
									</li>
									<li>
										對稱性
									</li>
									<li>
										螢光反應
									</li>
									<li>
										桌面大小
									</li>
									<li>
										深度
									</li>
									<li>
										底鑽
									</li>
									<li>
										規格大小
									</li>
									<li>
										證書
									</li>
									<li></li>
					
								</ul>
							</li>
		    <?php $i=0; foreach ($_items as $num => $_item):
			$i++;
			if ($i==5) break;
			?>	
			
							<li class="second-list-pop">
								<div class="top-pop-head">
									<img src="<?php echo $this->getskinurl("images")?>/popup-diamond-over.png" alt="" />
									<div class="rotate-show">
										<span class="rotate-360-pop"><img src="<?php echo $this->getskinurl("images")?>/360-deg.png" alt="" /></span>
										<span class="next-position"><img src="<?php echo $this->getskinurl("images")?>/small-diamond.png" alt="" /></span>
									</div>
								</div>
					
								<ul class="inner-pop-list second-inner">
									<li>
										<?php echo $_item->getName(); ?>
									</li>
					
									<li>
										
                                <?php echo  Mage::helper('core')->currency( $_item->getprice(),true,false) ;?>
									</li>
									<li>
							<?php echo 	$_item->getResource()->getAttribute('diamond_shape')->getFrontend()->getValue($_item);?>
									</li>
									<li>
								<?php echo 	$_item->getResource()->getAttribute('carat')->getFrontend()->getValue($_item);?>
									</li>
									<li>
									<?php echo 	$_item->getResource()->getAttribute('cut')->getFrontend()->getValue($_item);?>
									</li>
									<li>
									<?php echo 	$_item->getResource()->getAttribute('color_loose')->getFrontend()->getValue($_item);?>
									</li>
									<li>
									<?php echo 	$_item->getResource()->getAttribute('clarity')->getFrontend()->getValue($_item);?>
									</li>
									<li>
								<?php echo 	$_item->getResource()->getAttribute('polish')->getFrontend()->getValue($_item);?>
									</li>
									<li>
									<?php echo 	$_item->getResource()->getAttribute('symmetry')->getFrontend()->getValue($_item);?>
									</li>
									<li>
										<?php echo 	$_item->getResource()->getAttribute('fluorescence')->getFrontend()->getValue($_item);?>
									</li>
									<li>
										<?php echo number_format($_item->getDepth1(), 1) . '%'?>
									</li>
									<li>
										<?php echo number_format($_item->getTable(), 1) . '%'?>
									</li>
									<li>
						<?php echo 	$_item->getResource()->getAttribute('culet')->getFrontend()->getValue($_item);?>
										
									</li>
									<li class="mm-info"><?php echo $_item->getDimension() ?></li>
					
									<li>
										<?php echo $_item->getResource()->getAttribute('laboratory')->getFrontend()->getValue($_item) ;?>
									</li>
									<li  class="pop-add-cart"><a data="<?php echo  $_item->getid()?>" class="changer" href="javascript:void(0)" >調整鑽石</a></li>
					
								</ul>
								
								
							</li>
							<?php endforeach?>
					</ul>
<?php endif; ?>
<script type="text/javascript">
jQuery(".close-popup").click(function(){
   jQuery(".compaire-diamond-overlay").hide(); 
})
jQuery(".changer").click(function(){
  var d =	jQuery(this).attr("data");
  if (d == jQuery(".rings-display li.active").attr("data-d")){
	  jQuery(".compaire-diamond-overlay").hide(); 
  }
  var s =  jQuery(".rings-display li.active").attr("data-s");
  jQuery.ajax({
            url			: "<?php echo $this->geturl("*/ajax/recshow")?>",
			type : "POST",
            dataType	: "json",
            data		: {
                   "d" :   d,
				   "s" : s,
				   "update" : true
			},
            beforeSend	: function(){
               Advisor.Helper.startPreloader();
            },
            complete	: function(){

                Advisor.Helper.finishPreloader();
            },
            success		: function(data) {
			   jQuery("#recshow").html(data.show);
			     jQuery(".rings-display li.active").replaceWith(data.update);
				 jQuery(".compaire-diamond-overlay").hide();
            }
        });
})
</script>
</div>
</div>
</div>
</div>