
<?php if ($this->getCheckout()->getStepData('billing', 'complete')): ?>
<li class="complete">
    <a  href="#billing" onclick="checkout.changeSection('opc-billing'); return false;"><?php echo $this->__('Billing Address') ?>
  
   </a>
</li>
<dd class="complete">
    <address><?php echo $this->getBilling()->format('html') ?></address>
</dd>
<?php else: ?>
<li >
    <a <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?> class="active" <?php endif?> href="javascript:void(0)"><?php echo $this->__('Billing Address') ?></a>
</li>
<?php endif; ?>
