
<?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
<li class="complete">
    <a onclick="checkout.changeSection('opc-payment'); return false;"><?php echo $this->__('Payment Method') ?> </a>
</li>
<dd class="complete">
    <?php echo $this->getPaymentHtml() ?>
</dd>
<?php else: ?>
<li>
    <a href="javascript:void(0)"><?php echo $this->__('Payment Method') ?></a>
</li>
<?php endif; ?>

