
<?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
<?php $completeClass = $this->getCheckout()->getStepData('shipping', 'complete') ? 'complete' : ''; ?>
<li class="<?php echo $completeClass ?>">
   <a onclick="checkout.changeSection('opc-shipping'); return false;"> <?php echo $this->__('Shipping Address') ?> 
</a>
</li>
<dd class="<?php echo $completeClass ?>">
    <?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
    <address><?php echo $this->getShipping()->format('html') ?></address>
    <?php endif; ?>
</dd>
<?php else: ?>
<li>
   <a href="javascript:void(0)"> <?php echo $this->__('Shipping Address') ?></a>
</li>
<?php endif; ?>

