<?php /* @var Ikantam_Diamonds_Block_Product_Compare_Addtocompare */ ?>
<?php $id = md5($this->getAddUrl() . rand()); ?>
<span class="compare-container" id="<?php echo $id; ?>">
<input type="checkbox"
	class="add-to-compare" 
	data-add-url="<?php echo $this->getAddUrl();?>"
	data-remove-url="<?php echo $this->getRemoveUrl();?>"	
	<?php if($this->isComparing()):?>
	checked="checked"
	<?php endif;?>
/>
        
<img style="display:none" alt="Loading..." src="<?php echo $this->getSkinUrl("diamonds/images/loading.gif");?>" />
</span>
<script>
	jQuery(function(){
		new IkD.compareAjax("#<?php echo $id; ?>");		
	});
</script>
