<?php /* @var $this Ikantam_Diamonds_Block_Product_View_Diamond */ ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); 
$type= Mage::registry("design_type");
$_diamondsHelper = $this->helper('diamonds');
 $steps = array('diamonds'=>$this->__("Rings"),'engagement-rings'=>$this->__("Rings"),'earrings'=>$this->__("Earrings"),'pendants'=>$this->__("Pendants"));
$metal = $_product->getResource()->getAttribute('ring_metal')
->getFrontend()->getValue($_product);
$size = $_product->getResource()->getAttribute('ring_size')
->getFrontend()->getValue($_product);

 $price= $_product->getprice();
$price = Mage::helper('core')->currency($price,true,false) ;
preg_match("/[^0-9]+(.+)[\.](.+)/i",$price, $matches);
$price  = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
$price .= "<strong>".$matches[1]."<small>.".$matches[2]."</small></strong>";
?>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
			<section class="diamond-detail-banner">
					<div class="container">
						<ol class="breadcrumb">
                           <li><a href="<?php echo $this->getbaseurl()?>"><?php echo $this->__("Home")?></a></li>
                              <li><a href="#"><?php echo $this->__("Diamonds")?></a></li>
                            <li><a href="#"><?php echo $this->__("Design Diamonds")?></a></li>
                        </ol>
                        <h1><?php echo $this->__("Prensent Our Best For You")?></h1>
                       </div>
				</section>
				<section class="diamond-details page-content container">
		             <?php echo $this->getChildHtml("steps")?>
					<section class="tab-content diamond-details">
						<div class="left-block">
						    <?php echo Mage::helper("diamonds/media")->getmedia(null,$_product)->tohtml()?>
						<div class="right-block mob-right-block"></div>
						</div>
				       <div id="ad_sidebar" class="right-block ad_sidebar floating-sidebar">
				
							<h3><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
								<small>SKU : <?php echo $_product->getsku()?></small>
								</h3>
							<div class="product-info">
										<div class="product-info">
											<h2><?php echo $price?></h2>
											
											<ul class="product-info-d">
												<li><span class="card">
													<span class="desc-label"><?php echo $this->__("Metal")?></span>
													<span class="desc-val">
													
													<?php 
												$parents= 	 Mage::getModel('catalog/product_type_configurable')
                                             ->getParentIdsByChild( $_product->getId());
											 if(!$parents):
												echo $metal; 
												 
											 
											 else :
										    $parent = Mage::getmodel("catalog/product")->load($parents[0]);
											$children = Mage::getModel('catalog/product_type_configurable')  
											->getUsedProductCollection($parent);  
										 
												?>
											
										<select  id="metalselector">
										<?php foreach ($children as $child): 
										$child = Mage::getmodel("catalog/product")->load($child->getid());
											$metals = $child->getResource()->getAttribute('ring_metal')->getFrontend()->getValue($child);
										?>	
											 <?php $_selected = ($metals == $metal) ?' selected="selected"' : '' ?>
        <option                     value="<?php echo $child->getproducturl()?>"<?php echo $_selected ?>><?php echo $this->escapeHtml($metals) ?></option>
											  <?php endforeach; ?>
										</select>
								<script type="text/javascript">
								jQuery( "#metalselector" ).selectmenu({
									 change: function( event, ui ) {
										
										window.location=ui.item.value   
									  }
									});
								</script>
								<?php endif ; ?>
													</span>
												</span></li>
									
							
											</ul>
										</div>
													
							          
							    
							</div>
							<div class="star-label clearfix">
										<span class="rating">4.2</span>
										<div class="star-wrap">
											<ul class="page-label clearfix">
												<li class="color-g"></li>
												<li class="color-g"></li>
												<li class="color-g"></li>
												<li class="color-g"></li>
												<li></li>
											</ul>
											<span>(共有3個評慏）</span>
										</div>
									</div>
									<div class="btn-block">
	
	 <?php if ($type=="earrings"):?>
			 
	  <a href="javascript:void(0)" class="addlistbtn btn btn-block"><?php echo $this->__("Add a Single/Pair Earring")?></a>
	   <div class="addtoggle" style="display:none">
	  <a href="<?php echo Mage::getUrl("design/constructor/setting/type/earrings", array( 'ring_id' => $_product->getId(), '_nosid' => true)); ?>" class="btn btn-block"><?php echo $this->__("Add Single Earring")?></a>
	  <a href="<?php echo  Mage::getUrl("design/constructor/setting/type/earrings", array('qty' => 2 ,'ring_id' => $_product->getId(), '_nosid' => true)); ?>" class="btn btn-block"> <?php echo $this->__("Add a Pair of Earring")?></a>
       <a href="<?php echo Mage::getUrl("design/constructor/setting/type/earrings", array( 'ring_id' => $_product->getId(), '_nosid' => true)); ?>" class="btn btn-block"><?php echo $this->__("Add a Pair of Earring With Different Diamond")?></a>
	 </div>
  <script type="text/javascript">
	  jQuery(".addlistbtn").click(function(e){
		  jQuery(".addtoggle").slideToggle(500);
		  e.stopprogration();
	  })
	  </script>	 
	 <?php else :?>

		<a href="<?php echo $_diamondsHelper->getSelectSettingUrl($_product); ?>size/<?php echo $size?>" class="btn btn-block"><?php echo $this->__("Add to Diamond ")?><?php echo  $steps[$type]?></a>

	<?php endif ?>
		  <?php if ($_product->isSaleable()): ?>
		
				<a href="<?php echo $this->getAddToCartUrl($_product) ?>" 
				
				class="btn btn-block"><?php echo $this->__("Add to Cart")?></a>

			<?php else: ?>
			<p class="availability out-of-stock">
				<span><?php echo $this->__('Out Of Stock') ?> </span>
			</p>
		<?php endif; ?>
	
		</div>
							
		<span class="delivery-date"><?php echo __("Estimate the Fastest Delivery Time")?>: <span class="date">2015-11-10</span></span>
		<div class="share-links">
			<ul class="social-links">
				<li><a href="#"><img src="<?php echo $this->getskinurl("images/side-fb-link.png")?>" alt="" /></a></li>
				<li><a href="#"><img src="<?php echo $this->getskinurl("images/side-tt-link.png")?>" alt="" /></a></li>
				<li><a href="#"><img src="<?php echo $this->getskinurl("images/side-print-link.png")?>" alt="" /></a></li>
				<li><a href="#"><img src="<?php echo $this->getskinurl("images/side-insta-link.png")?>" alt="" /></a></li>
			</ul>
			<div class="external-links">

				<a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>" class="mail-to-frnd"><i class="icon-mail-link">&nbsp;</i><span><?php echo $this->__('Email To Friend') ?></span></a>
		
			<?php if ($this->helper('wishlist')->isAllow()) : ?>
			<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>
				<a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;"class="mail-to-frnd"><i class="icon-wishlist-link">&nbsp;</i><span><?php echo $this->__('Add to Wishlist') ?></span></a>
				<?php endif ?>	
			</div>
		</div>			
						</div>
			
					</section>


                 </section>
				 
       <script>
	        var sidebar = jQuery("#ad_sidebar").html();

        jQuery(".mob-right-block").html(sidebar);
		function setRingSize()
		{	
			var newLocation = "<?php echo $this->helper('diamonds')->getSelectSettingUrl($_product); ?>";
			location.href = newLocation;
		}
		
		function addToCartRing()
		{
			var selectedSize = document.getElementById("selected_ring_size").value;
			/*var diamondId = "<?php /*echo $_product->getId();*/ ?>";*/
			var newLocation = "<?php echo $this->helper('diamonds')->getAddRingToCartUrl($_product); ?>";
			/*'product/' + diamondId*/
			location.href = newLocation +  'size/' + selectedSize;
		}
        </script>

</div>