<aside class="aside tab-aside">
<ul>
<li  class="dark-color active-heading"><a id="styletab" class="active" href="#ringtab1"><span class="tab-number">1</span>  <span class="ra-tab-heading"><?php echo $this->__("Ring Style")?></span></a></li>
<li  class="light-color"><a id="qualitytab" href="#ringtab2"><span class="tab-number">2</span>  <span class="ra-tab-heading"><?php echo $this->__("Ring Quality")?></span></a></li>
<li  class=""><a id="recommendtab" href="#ringtab3"><span class="tab-number">3</span> <span class="ra-tab-heading"><?php echo $this->__("Ring Recommend")?></span></a></li>
</ul>
<div class="top"><img alt="" src="<?php echo $this->getskinurl("images/")?>ringadvisor-1.jpg" />
<div class="top-text"><span><?php echo $this->__("Hot")?></span></div>
</div>
</aside>