<div class="pager css3 row-fluid show-grid">
	<div class="sort-by span2">
		<?php echo $this->getChildHtml('filter_toolbar_sort')?>
	</div>

	<p class="view-mode span3">
		<?php echo $this->getChildHtml('filter_toolbar_mode')?>
	</p>

	<div class="limiter span4">
		<?php echo $this->getChildHtml('filter_toolbar_limiter')?>
	</div>

	<div class="span3 pageBlock">
		<?php echo $this->getPagerHtml();?>
	</div>

</div>

