<?php
/* @var $config Ikantam_Diamonds_Helper_Config */
$config = $this->helper('diamonds/config');
?>

<?php $attributeMetalOptions = $this->getAttributeOptions('ring_metal'); ?>
<!--SHAPE-->
 <ul class="shapes-design clearfix">
        <?php foreach ($attributeMetalOptions as $option): ?>
				          <li>  
            <input  class="metal-input metal"  type="checkbox" value="<?php echo $option->getId(); ?>" id="metal<?php echo $option->getId(); ?>">
            <label for="metal<?php echo $option->getId(); ?>">
		
			<?php echo $option->getValue(); ?></label>       
         </li>
    
        <?php endforeach; ?>
    </ul>
<script type="text/javascript">
    jQuery(function(jQuery){
        /*Color-----*/
            jQuery("input.metal").click(function(){
                var selected = jQuery(this).attr("data-selected");
        		
                if(selected == "true"){
                    jQuery(this).attr("data-selected","false");
        			
                } else {
                    jQuery(this).attr("data-selected", "true");
        			
                }
				 ringsFilter.updateResults(); 
        		
            });
        		
       var getDataMetal = function(){
            var metals = jQuery(".metal-input");
            var mass = new Array();
            for(var i=0;i<metals.length;i++){
                var metal = jQuery(metals[i]);
                if(metal.attr("data-selected") == "true" ){
                    mass.push(metal.attr("value"));
                }		
            }
            return { mass : mass };
        };

    
             ringsFilter.registerFilter("ring_metal", getDataMetal);
    });
</script>
