<h2><?php echo $this->__("Budget")?></h2> 
<form id="budgetform" class="price-add-form" action="" method="get">
<?php $currency = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?>
<fieldset><select id="price-category" name="price-category">
<option value="" selected="selected"><?php echo $this->__("Price Range")?></option>
<option value="1000,4999"><?php echo $currency ?>1,000-<?php echo $currency ?>4,999</option>
<option value="5000,9999"><?php echo $currency ?>5,000-<?php echo $currency ?>9,999</option>
<option value="10000,2999"><?php echo $currency ?>10,000-<?php echo $currency ?>29,999</option>
<option value="30000,59999"><?php echo $currency ?>30,000-<?php echo $currency ?>59,999</option>
<option value="50000"><?php echo $currency ?>50,000 <?php echo $this->__("And Above")?></option>
</select></fieldset>
<fieldset>
<select id="address-category" name="address-category">
<option selected="selected"><?php echo $this->__("Jewelry Type")?></option>
<option value="diamond" ><?php echo $this->__("Diamonds")?></option>
<option value="engagement" ><?php echo $this->__("Engagement Rings")?></option>
<option value="wedding"><?php echo $this->__("Wedding Rings")?></option>
<option value="earring"><?php echo $this->__("Earrings")?></option>
<option value="pendant"><?php echo $this->__("Pendants")?></option>
<option value="bracelet"><?php echo $this->__("Bracelets")?></option>
</select></fieldset>
<div id="gender_category" class="checkbox-list " style="visibility:hidden">
<p><input id="radio1" type="radio" checked="checked" name="check1" /> <label for="radio1"> <?php echo $this->__("Women")?></label></p>
<p><input id="radio2" type="radio" name="check1" /> <label for="radio2"><?php echo $this->__("Man")?>  </label></p>
</div>
<button class="know-more-btn" type="submit"> <span> <?php echo $this->__("Know More")?></span> </button></form>
<script type="text/javascript">
  jQuery("#address-category").selectmenu({
  change: function(){
	  if (jQuery(this).val()=="wedding"){
	  jQuery("#gender_category").css("visibility","visible");
	  }
	  else{
		jQuery("#gender_category").css("visibility","hidden");  
	  }
	switch(jQuery(this).val()){
		 case "diamond":
		 var url = "<?php echo $this->geturl('design/diamond/index/type/diamonds') ?>"
		 break;
		 case "engagement":
		var url = "<?php echo $this->geturl('design/settings/index/type/engagement-rings') ?>"
	     break;
		  case "wedding":
		 var url = "<?php echo $this->geturl('wedding-ring.html')?>"
	     break;
		  case "earring":
		var url = "<?php echo $this->geturl('design/settings/index/type/earrings') ?>"
	     break;
		  case "pendant":
				var url = "<?php echo $this->geturl('design/settings/index/type/pendants') ?>"
	     break;
		   case "bracelet":
		 var url = "<?php echo $this->geturl('bracelet.html')?>"
	     break;
	 }
     jQuery("#budgetform").attr("action",url)
  }
  })
</script>