<?php /* @var $this Ikantam_Diamonds_Block_Product_Similar_List */ ?>
<?php
    $_productCollection=$this->getProductCollection();
    $_helper = $this->helper('catalog/output');
    $_diamondsHelper = $this->helper('diamonds');
?>

<?php if( is_array($_productCollection) || !$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

<div class="products-grid row-fluid show-grid">
<div id="diamonds-filter-results">

<div class="category-products">
    
    <?php // Grid Mode ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = 4; //$this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <div class="products-grid row-fluid show-grid">
        <?php endif ?>
            <div class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> span3">
                <div class="item-inner">
                    <a href="<?php echo $_diamondsHelper->getDiamondUrl($_product); ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" id="product_<?php echo $_product->getId() ?>">
                    	<div id="<?php echo $_product->getId();?>">
                    	<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(226); ?>" width="226" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    	</div>
                    </a>
                    <h2 class="product-name"><a href="<?php echo $_diamondsHelper->getDiamondUrl($_product); ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <div class="actions">  
                    	
                    	<!-- IkD -->
                    	<button type="button" class="button" onclick="location.href='<?php echo $_diamondsHelper->getAddToRingUrl($_product);?>'" >
                    		<span><?php echo $this->__('Add to ring') ?></span>
                    	</button>
                    	<!-- IkD -->
                        
                        <?php if($_product->isSaleable()): ?>
                        	<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="ajaxaddcart('<?php echo $this->getAddToCartUrl($_product) ?>',<?php echo $_product->getId() ?>)"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php } else { ?>
                        	<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        	<a href='<?php echo $this->getUrl('mtgeroadmin/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Add</a>
                        	<?php }?> 
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <!--<ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>-->
                    </div>
                </div>
            </div>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </div>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
</div>
</div>
</div>
<?php endif; ?>