                 <!-- 	newsletter-start----->  	   
				<section class="newsletter-sec newsletter-sec-new">
					<div class="container">
						<div class="newsletter-wrapper clearfix">
						<div class="newsletter"> 
						<h2><?php echo $this->__("SIGN UP FOR OUR NEWS AND SALES")?></h2>
                       <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
							<input id="subscribe_email" class="form-field" name="email" placeholder="<?php echo $this->__("Input Your Email Address")?>" type="email">
							<button class="sub" type="submit"><?php echo $this->__("Submit")?></button>
						</form>
						</div>
						<div class="social-wrapper">
							<h2><?php echo $this->__("Follow Us")?></h2>
							<ul class="clearfix">
								<li><a href="#">
									<img src="<?php echo $this->getskinurl("images/fb-icon.png")?>" alt="#">
								</a></li>
								<li><a href="#">
									<img src="<?php echo $this->getskinurl("images/twt-icon.png")?>" alt="#">
								</a></li>
								<li><a href="#">
									<img src="<?php echo $this->getskinurl("images/inst-icon.png")?>" alt="#">
								</a></li>
								<li><a href="#">
									<img src="<?php echo $this->getskinurl("images/print-icon.png")?>" alt="#">
								</a></li>
							</ul>
						</div>
						</div>
					</div>
				</section>
				
				
				
				<!-- 	newsletter-end----->  



