


<?php
$_product = $this->getProduct();

$options = $_product->getAttributeText('giftcard_template');
if(is_array($options))
$firsttemp=reset($options);
if(!isset($firsttemp))
$firsttemp="";
?>


   


<style type="text/css">
    .box{
       
        display: none;
        margin-top: 10px;
        border: 1px  #000;
    }
    .customform{ background: #fff; }
   td{
  
   padding:2px 2px;
   }
.price-info{
display:none;
}
</style>
<script src="<?php echo $this->getSkinUrl('js/giftcard/jquery.min-1.11.1.js') ?>"></script>  
<script type="text/javascript">
var gc=$.noConflict();

    gc(document).ready(function(){
        gc('input[type="checkbox"]').click(function(){
            if(gc(this).attr("value")=="customform"){
                gc(".customform").toggle();
            }
          
        });
     
     
     gc("#giftcard_template").change(function() {
          var templat = gc('option:selected',gc(this)).text(); 
          var trimtemplat = gc.trim(templat)
            gc("#template").val(trimtemplat);
        });
        
    gc("#txt1").keyup(function(){
   gc("#from").html(gc(this).val());
   gc("#from1").html(gc(this).val());
});
  gc("#txt2").keyup(function(){
   gc("#to").html(gc(this).val());
   gc("#to1").html(gc(this).val());
});

 gc("#txt1").blur(function(){
   gc("#from").html(gc(this).val());
   gc("#from1").html(gc(this).val());
});
  gc("#txt2").blur(function(){
   gc("#to").html(gc(this).val());
   gc("#to1").html(gc(this).val());
});

gc('#tb1').keyup(function(e){
      var keyed = gc(this).val().replace(/[\n]/g,'<br />');
      gc("#txtCustName").html(keyed);
      gc("#txtCustName1").html(keyed);
 });
 
 gc('#tb1').blur(function(e){
      var keyed = gc(this).val().replace(/[\n]/g,'<br />');
      gc("#txtCustName").html(keyed);
      gc("#txtCustName1").html(keyed);
 });

    });
</script>




									<div class="form-group">
										<label class="cp-label">由：</label>
										<input type="text" placeholder="" name="SenderName" id='txt1' class="required-entry cp-input" />
									</div>
									<div class="form-group">
										<label class="cp-label">送給：</label>
										<input type="text" name="ReciptentName" id='txt2' placeholder="" class="required-entry cp-input" />
									</div>
									<div class="form-group">
										<label class="cp-label">您的話語：</label>
										<textarea    id='tb1' name="CustomMessage" class="cp-input required-entry cp-text"></textarea>
									</div>
									<div class="form-group date-group">
										<label class="cp-label cp-date">送出日期：</label>
										 <input type="text" style="width: 120px;line-height: 20px;font-size: 15px;" class="required-entry input-text" value="" id="selected_date" name="DeliveryDate"/>
      <img style="display:inline;" title="Select Date" id="date_select_trig" class="v-middle" alt="" src="<?php
echo $this->getSkinUrl('images/calendar.gif'); ?> "/>
									</div>
									<div class="form-group">
										<label class="cp-label">收件者電郵：</label>
										<input type="email" name="RecipientEmail" id='txt3' placeholder="" class="validate-email required-entry cp-input" />
									</div>
    <div>
        <label><input style="display:none" type="checkbox" checked="checked" name="colorCheckbox" value="customform"><?php echo $this->__('') ?> </label>
     
    </div>
    <input type="hidden" name="Template" id='template' value="<?php echo $firsttemp; ?>" class="input-text " >

  
    <script type="text/javascript">
    // <![CDATA[
        Calendar.setup({
            inputField: "selected_date",
            ifFormat: "%m/%e/%Y ",
            showsTime: true,
            button: "date_select_trig",
            align: "Bl",
            singleClick : true
        });
    // ]]>
    </script>
</span>

    
   
  
 


