<?php /* @var $this Ikantam_Diamonds_Block_Product_List_Diamonds */ ?>
<?php
$_productCollection = $this->getProductCollection();
$_helper = $this->helper('catalog/output');
$_diamondsHelper = $this->helper('diamonds/bracelet');
?>
<?php echo $this->getChildHtml("toolbar_top");
 ?>


<?php if (!$_productCollection->count()): ?>

    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
      <div id="tab-grid" class="diamond-grid-list">
		<div class="search-content">
		<ul class="search-list-wrap clearfix">
      <?php // Grid Mode  ?>
                    <?php $_collectionSize = $_productCollection->count() ?>
                    <?php $_columnCount = 4; //$this->getColumnCount(); ?>
                    <?php $i = 0;
                    foreach ($_productCollection as $_product):
                        ?>
			<li>
			<div class="slider-small search-item">
			<figure>
			<div data-id="<?php echo $_product->getId() ?>" class="viewbutton quick_view_trigger">快速欣賞</div>
			<a
			href="<?php echo $_diamondsHelper->getSettingUrl($_product); ?>"
			title="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>"
			class="product-image" style="height: 100%; width: 100%;"
			id="product_<?php echo $_product->getId() ?>">

			<img alt="diamond" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(141); ?>" />
				
			</a>
			</figure>
			<h3><a href="<?php echo $_diamondsHelper->getSettingUrl($_product); ?>"
			 title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
			 <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
			 </a>
			 </h3>
			<span class="diamond-properties"> 
			<span>質材:<?php echo $_product->getResource()->getAttribute('ring_metal')->getFrontend()->getValue($_product)?></span> 
	
			<div class="star-label clearfix"><span class="rating">4.2</span>
			<div class="star-wrap"><span>(共有3個評慏）</span></div>
			</div>
			<span class="norm"><?php echo Mage::helper("core")->currency($_product->getFinalPrice()) ?>
			</span>

               </div>
			</li>
			<?php endforeach ?>
			</ul>
			</div>
			</div>
	   
    <script type="text/javascript">

            jQuery(function($) {
				$(".viewbutton").click(function(){
			     var id =$(this).attr("data-id");
					if($("#absoluteDiv"+id).length=="0"){
						         jQuery(".overlayBlock").show();	
						$.ajax({
								 type: 'GET',
								 url: '<?php echo $this->geturl("design/earrings_quickview/view/part/setting")?>' ,
								 data: "id="+id,
								 success: function(data){
								$("body").append(data); 
								  
								 } ,
								dataType: "json"
							});	
							
					}
					else {
						$("#absoluteDiv"+id).show();
					}
					
				});
            });
			</script>
<?php endif; ?>