<div class="content-description">
<div class="content-head">
<h2><span>2</span> <?php echo __("Which Style do you Like")?>？</h2>
</div>
<form class="select-ring">
<ul id ="ring-style" class="clearfix">
<li class="filter"  data-filter="Halo"><label class="ring1" for="ring-1"><span></span> <?php echo __("Halo")?></label></li>
<li class="filter"  data-filter="Solitaire"><label  class="ring2" for="ring-2"><span></span> <?php echo __("Solitaire")?></label></li>
<li class="filter"  data-filter="Masterwork"><label  class="ring3" for="ring-3"><span></span> <?php echo __("Masterwork")?></label></li>
<li class="filter"  data-filter="Three Stone"><label  class="ring4" for="ring-4"><span></span> <?php echo __("Three Stone")?></label></li>
</ul>
</form>
<div class="content-product-description content-product-description-one clearfix"><span class="flash-diamond"> <strong><?php echo __("Halo")?></strong> <small><?php echo __("The center of Halo Consist of little diamond.")?></small> </span>
<h2>20<span>%</span> <em><?php echo __("Customer Choose")?></</em></h2>
</div>
<div class="content-product-description content-product-description-two clearfix">
<div class="description-text">
<h2 class="aura"><?php echo __("Halo")?> <strong>20%</strong> <small><?php echo __("Customer Choose")?></small></h2>
<span><?php echo __("The center of Halo Consist of little diamond.")?></span></div>
<div class="description-text description-right">
<h2 class="aura"><?php echo __("Solitaire")?> <strong>32%</strong> <small><?php echo __("Customer Choose")?></small></h2>
<span><?php echo $this->__("Single Diamond Deisign,Simply Bright,Suit for Man like to be Simple.")?></span></div>
</div>
<div class="content-product-description content-product-description-three clearfix">
<div class="description-text">
<h2 class="aura"><?php echo __("Halo")?> <strong>20%</strong> <small><?php echo __("Customer Choose")?></small></h2>
<span><?php echo __("The center of Halo Consist of little diamond.")?></span></div>
<div class="description-text description-right">
<h2 class="aura"><?php echo __("Solitaire")?> <strong>32%</strong> <small><?php echo __("Customer Choose")?></small></h2>
<span><?php echo $this->__("Single Diamond Deisign,Simply Bright,Suit for Man like to be Simple.")?></span></div>
<div class="description-text">
<h2 class="aura"><?php echo __("Masterwork")?> <strong>24%</strong> <small><?php echo __("Customer Choose")?></small></h2>
<span><?php echo __("The Thin Diamond beset by whole Ring,Elegant.")?></span></div>
</div>
<div class="content-product-description content-product-description-four clearfix">
<div class="description-text">
<h2 class="aura"><?php echo __("Halo")?> <strong>20%</strong> <small><?php echo __("Customer Choose")?></small></h2>
<span><?php echo __("The center of Halo Consist of little diamond.")?></span></div>
<div class="description-text description-right">
<h2 class="aura"><?php echo __("Solitaire")?> <strong>32%</strong> <small><?php echo __("Customer Choose")?></small></h2>
<span><?php echo $this->__("Single Diamond Deisign,Simply Bright,Suit for Man like to be Simple.")?></span></div>
<div class="description-text">
<h2 class="aura"><?php echo __("Masterwork")?> <strong>24%</strong> <small><?php echo __("Customer Choose")?></small></h2>
<span><?php echo __("The Thin Diamond beset by whole Ring,Elegant.")?></span></div>
<div class="description-text description-right">
<h2 class="aura"><?php echo __("Three Stone")?> <strong>24%</strong> <small><?php echo __("Customer Choose")?></small></h2>
<span><?php echo __("Tree diamonds,one for main diamond,two for side diamond,build to be gorgeous.")?></span></div>
</div>
</div>
<div class="content-fig">
<div class="content-fig-one clearfix">
<div class="description-fig">
<div class="description-fig-content"><img alt="" src="<?php echo $this->getskinurl("images/")?>ringadvisor-35.png" /></div>
</div>
</div>
<div class="content-fig-two">
<div class="description-fig">
<div class="description-fig-content"><img alt="" src="<?php echo $this->getskinurl("images/")?>ringadvisor-5.jpg" /> <span class="ring-name"><?php echo __("Halo")?></span></div>
</div>
<div class="description-fig">
<div class="description-fig-content"><img alt="" src="<?php echo $this->getskinurl("images/")?>ringadvisor-6.jpg" /> <span class="ring-name"><?php echo __("Solitaire")?></span></div>
</div>
<div class="description-fig hidemob">&nbsp;</div>
<div class="description-fig hidemob">&nbsp;</div>
</div>
<div class="content-fig-three">
<div class="description-fig">
<div class="description-fig-content"><img alt="" src="<?php echo $this->getskinurl("images/")?>ringadvisor-5.jpg" /> <span class="ring-name"><?php echo __("Halo")?></span></div>
</div>
<div class="description-fig">
<div class="description-fig-content"><img alt="" src="<?php echo $this->getskinurl("images/")?>ringadvisor-6.jpg" /> <span class="ring-name"><?php echo __("Solitaire")?></span></div>
</div>
<div class="description-fig">
<div class="description-fig-content"><img alt="" src="<?php echo $this->getskinurl("images/")?>ringadvisor-7.jpg" /> <span class="ring-name"><?php echo __("Masterwork")?></span></div>
</div>
<div class="description-fig">&nbsp;</div>
</div>
<div class="content-fig-four">
<div class="description-fig">
<div class="description-fig-content"><img alt="" src="<?php echo $this->getskinurl("images/")?>ringadvisor-5.jpg" /> <span class="ring-name"><?php echo __("Halo")?></span></div>
</div>
<div class="description-fig">
<div class="description-fig-content"><img alt="" src="<?php echo $this->getskinurl("images/")?>ringadvisor-6.jpg" /> <span class="ring-name"><?php echo __("Solitaire")?></span></div>
</div>
<div class="description-fig">
<div class="description-fig-content"><img alt="" src="<?php echo $this->getskinurl("images/")?>ringadvisor-7.jpg" /> <span class="ring-name"><?php echo __("Masterwork")?></span></div>
</div>
<div class="description-fig">
<div class="description-fig-content"><img alt="" src="<?php echo $this->getskinurl("images/")?>ringadvisor-8.jpg" /> <span class="ring-name"><?php echo __("Three Stone")?></span></div>
</div>
</div>
</div>

<script type="text/javascript">
styleFilter.addfilter("ring-style");
jQuery('#ring-style li.filter').bind('click',function(){
	
	if(jQuery(this).hasClass("disable")){
		return false;
	}
	jQuery(this).siblings(".filter").removeClass("active");
    jQuery(this).toggleClass('active');
	jQuery(this).parents('.content-2').removeClass("open-show1").removeClass("open-show2").removeClass("open-show3").removeClass("open-show4");
	jQuery(this).parents('.content-2').addClass('open-show'+jQuery(this).children('label').attr("class").replace('ring',''));
	styleFilter.applyfilter();
	
	});


</script>