	<ul class="social-links">
				<li><a onclick="SendSNS('facebook','<?php echo $this->getname()?>','<?php echo $this->getUrl()?>');" href="javascript:void(0)"><img src="<?php echo $this->getskinurl("images/side-fb-link.png")?>" alt="" /></a></li>
				<li><a  onclick="SendSNS('twitter','<?php echo $this->getname()?>','<?php echo $this->getUrl()?>');" href="javascript:void(0)"><img src="<?php echo $this->getskinurl("images/side-tt-link.png")?>" alt="" /></a></li>
				<li><a  onclick="SendSNS('sina','<?php echo $this->getname()?>','<?php echo $this->getUrl()?>');" href="javascript:void(0)"><img src="<?php echo $this->getskinurl("images/side-print-link.png")?>" alt="" /></a></li>
				<li><a  onclick="SendSNS('instagram','<?php echo $this->getname()?>','<?php echo $this->getUrl()?>');" href="javascript:void(0)"><img src="<?php echo $this->getskinurl("images/side-insta-link.png")?>" alt="" /></a></li>
			</ul>