<?php /* @var $this Ikantam_Diamonds_Block_Filter */ ?>


            <?php echo $this->getChildHtml("filters"); ?>
     

<script type="text/javascript">
    var updateUrl = "<?php echo $this->getBaseUrl() . 'design/engagementrings_filter/diamond'; ?>";
    var diamondsFilter = new IkD.Filter(updateUrl, null);
    jQuery(function(){
        diamondsFilter.setResultContainer(jQuery("#diamonds-filter-results"));
    });
	

	var $dropBtn = jQuery('#ikantam-mage-filter .drop-list .dropdown-toggle'),
	$list    = jQuery('#ikantam-mage-filter ul.dropdown-menu');
	$dropBtn.on('click', function(){
		$dropBtn.toggleClass('ison');
		$list.toggle();
	});

</script>


<!-- end init -->



