<?php /* @var $this Mage_Core_Block_Template */?>
<div id="compare-list" class="category-products">
<!--  
	<div class="toolbar css3">
		<div class="pager css3 row-fluid show-grid">
			<div class="sort-by span3">
				<label>Sort By</label> <select onchange="setLocation(this.value)">
					<option
						value="http://diamonds.webbos.co/magento/men.html?dir=asc&amp;order=position"
						selected="selected">Color</option>
					<option
						value="http://diamonds.webbos.co/magento/men.html?dir=asc&amp;order=name">Carat</option>
					<option
						value="http://diamonds.webbos.co/magento/men.html?dir=asc&amp;order=price">Clarity</option>
					<option
						value="http://diamonds.webbos.co/magento/men.html?dir=asc&amp;order=price">Cut</option>
					<option
						value="http://diamonds.webbos.co/magento/men.html?dir=asc&amp;order=price">Price</option>
				</select> <a
					href="http://diamonds.webbos.co/magento/men.html?dir=desc&amp;order=position"
					title="Set Descending Direction"><img
					src="http://diamonds.webbos.co/magento/skin/frontend/default/mt_gero/images/i_asc_arrow.gif"
					alt="Set Descending Direction" class="v-middle"> </a>
			</div>
		</div>
	</div>
	-->
	<!-- /toolbar css3-->
<?php echo $this->getChildHtml("diamonds_comparasion_list"); ?>
</div>