<h3 class="mob-heading clearfix">
	<a href="#" class="w1 currency"><?php echo __("Currency")?> </a>
							
	<a href="#" class="w2 delevery-option"><?php echo __("Delivery")?></a>
							</h3>
<div class="search-box search-mob">
						   <?php 
						   
						   echo $this->getParentBlock()->getParentBlock()->getChildHtml('topSearch'); ?>
							</div>						
							<nav>
								<ul class="clearfix">
									<li class="diamond-sub-list-container">
										<a class="parent" href="javascript:void(0)"><?php echo __("Diamonds")?></a>
										<ul class="primary-sub-menu">
											<li class="diamond-sublist-wrapper">
												
												<div class="container clearfix">
												<div class="primary-sub-menu-list clearfix">
													<h2 class="sub-arr-icon"><a href="javascript:void(0)"><?php echo __("Store")?></a></h2>
													<ul>
													
													<!-- <li><a href="<?php echo $this->geturl("diamonds-only.html")?>"><?php echo __("All Diamonds")?></a></li> -->
													<li><a href="<?php echo $this->geturl("design/diamond/index/type/diamonds")?>"><?php echo __("Design Your Diamonds")?></a></li>
												</ul>
												</div>
												
												<div class="secondry-sub-menu-list clearfix">
													<h2><a href="javascript:void(0)">  <?php echo __("Diamond Shape")?></a></h2>
													<ul>
											     
											       <li><a href="<?php echo $this->geturl("design/diamond/index/type/diamonds")?>?shape=Round"><i class="diamond-list-icon a"></i><?php echo __("Round Cut")?></a></li>
											       <li><a href="<?php echo $this->geturl("design/diamond/index/type/diamonds")?>?shape=Princess"><i class="diamond-list-icon b"></i><?php echo __("Princess Cut")?></a></li>
											       <li><a href="<?php echo $this->geturl("design/diamond/index/type/diamonds")?>?shape=Emerald"><i class="diamond-list-icon c"></i><?php echo __("Emerald Cut")?></a></li>
											       <li><a href="<?php echo $this->geturl("design/diamond/index/type/diamonds")?>?shape=Asscher"><i class="diamond-list-icon d"></i><?php echo __("Asscher Cut")?></a></li>
											       <li><a href="<?php echo $this->geturl("design/diamond/index/type/diamonds")?>?shape=Marquise"><i class="diamond-list-icon e"></i><?php echo __("Oval Cut")?></a></li>
											       <li><a href="<?php echo $this->geturl("design/diamond/index/type/diamonds")?>?shape=Radiant"><i class="diamond-list-icon f"></i><?php echo __("Radian Cut")?></a></li>
											       <li><a href="<?php echo $this->geturl("design/diamond/index/type/diamonds")?>?shape=Triangle"><i class="diamond-list-icon g"></i><?php echo __("Triangle Cut")?></a></li>
											       <li><a href="<?php echo $this->geturl("design/diamond/index/type/diamonds")?>?shape=Pear"><i class="diamond-list-icon h"></i><?php echo __("Pear Cut")?></a></li>
											       <li><a href="<?php echo $this->geturl("design/diamond/index/type/diamonds")?>?shape=Heart"><i class="diamond-list-icon i"></i><?php echo __("Heart Cut")?></a></li>
											       <li><a href="<?php echo $this->geturl("design/diamond/index/type/diamonds")?>?shape=Cushion"><i class="diamond-list-icon j"></i><?php echo __("Cushion Cut")?></a></li>
										        </ul>
												</div>
										        
										        <div class="third-sub-menu-list">
										        	<h2><?php echo $this->__("Knowledge")?></h2>
										        	<div class="clearfix">
										        		<img title=" " alt=" " src="<?php echo $this->getskinurl("images/") ?>engage-sub-list-img.jpg">
										        		<ul>
										        			<li><a href="<?php echo $this->geturl("knowledge-diamond")?>"><?php echo $this->__("About Diamond")?></a></li>
										        			<li><a href="<?php echo $this->geturl("knowledge-diamond-shape")?>"><?php echo $this->__("About Diamond Shape")?></a></li>
										        			<li><a href="<?php echo $this->geturl("knowledge-diamond-cert")?>"><?php echo $this->__("About Certificate")?></a></li>
										        			<li><a href="<?php echo $this->geturl("knowledge-engagement")?>"><?php echo $this->__("About Maintain")?></a></li>
										        			<li><a href="<?php echo $this->geturl("knowledge-engagement")?>"><?php echo $this->__("About Diamond Params")?></a></li>
										        		</ul>
										        	</div>
										        </div>
										        
										        </div>
										</li>
										</ul>
										
										
										
									</li>
									<li class="engaged-ring-sub-list">
										<a class="parent" href="javascript:void(0)"><?php echo $this->__("Engagement Rings")?></a>
										<ul class="primary-sub-menu">
											<li class="diamond-sublist-wrapper">
												
												<div class="container clearfix">
												<div class="primary-sub-menu-list clearfix">
													<h2 class="sub-arr-icon"><a href="javascript:void(0)"><?php echo $this->__("Store")?></a></h2>
													<ul>
													
													<!--<li><a href="javascript:void(0)"><?php echo $this->__("All Diamonds")?></a></li>-->
													<li><a href="<?php echo $this->geturl("design/settings/index/type/engagement-rings")?>"><?php echo $this->__("Design Your Engagement Rings")?></a></li>
												</ul>
												</div>
												
											 <div class="third-sub-menu-list">
										        	<h2><?php echo $this->__("Knowledge")?></h2>
										        	<div class="clearfix">
										        		<img src="<?php echo $this->getskinurl("images/") ?>sub-menu-img1.jpg" alt=" " title=" " />
										        		<ul>
										        			<li><a href="<?php echo $this->geturl("knowledge-engagement-how-to-buy")?>"><?php echo $this->__("Choose Engagement Rings")?></a></li>
										        			<li><a href="<?php echo $this->geturl("knowledge-engagement-conflict")?>"><?php echo $this->__("Conflict Diamonds")?></a></li>
										        			<li><a href="<?php echo $this->geturl("knowledge-engagement-type")?>"><?php echo $this->__("Ring Type")?></a></li>
										        			<li><a href="<?php echo $this->geturl("knowledge-engagement-size")?>"><?php echo $this->__("Ring Size")?></a></li>
										        			<li><a href="<?php echo $this->geturl("knowledge-engagement-surface")?>"><?php echo $this->__("Rings Surface Clean")?></a></li>
										        		</ul>
										        	</div>
										        </div>
										       
										        
										        </div>
										</li>
										</ul>
									</li>
									
									
									<li class="wedding-ring-sub-list">
										<a class="parent" href="javascript:void(0)"><?php echo $this->__("Wedding Rings")?></a>
										<ul class="primary-sub-menu">
											<li class="diamond-sublist-wrapper">
												
												<div class="container clearfix">
												<!-- <div class="primary-sub-menu-list clearfix">
													<h2 class="sub-arr-icon"><a href="javascript:void(0)"><?php echo $this->__("Store")?></a></h2>
														<ul>
														
														<li><a href="<?php echo $this->geturl("wedding-ring.html")?>"><?php echo $this->__("All Wedding Rings")?></a></li>
														
													</ul>
												</div> -->
												

												
												<div class="secondry-sub-menu-list clearfix">
													<h2><a href="javascript:void(0)"> <?php echo $this->__("Vows")?></a></h2>
													<ul>
											     
											       <li><a href="<?php echo $this->geturl("wedding-ring")?>man.html"> <?php echo $this->__("Man Styles")?></a></li>
											      
										        </ul>
										    
													<ul>
											     
											       <li><a href="<?php echo $this->geturl("wedding-ring")?>woman.html"> <?php echo $this->__("Women Style")?></a></li>
											      
										        </ul>
												</div>
										        
										        <div class="third-sub-menu-list">
										        	<h2><?php echo $this->__("Knowledge")?></h2>
										        	<div class="clearfix">
										        		<img src="<?php echo $this->getskinurl("images/") ?>wedding-sub-list-img.jpg" alt=" " title=" " />
										        		<ul>
										        			<li><a href="<?php echo $this->geturl("knowledge-engagement-how-to-buy")?>"> <?php echo $this->__("Choose Wedding Rings")?></a></li>
							
										        			<li><a href="<?php echo $this->geturl("knowledge-engagement-type")?>"> <?php echo $this->__("Ring Type")?></a></li>
										        			<li><a href="<?php echo $this->geturl("knowledge-engagement-size")?>"> <?php echo $this->__("Ring Size")?></a></li>
										        			<li><a href="<?php echo $this->geturl("knowledge-engagement-surface")?>"> <?php echo $this->__("Rings Surface Clean")?></a></li>

										        		</ul>
										        	</div>
										        </div>
										        
										        </div>
										</li>
										</ul>
									</li>
									<li class="jewelry-sub-list">
										<a class="parent" href="javascript:void(0)"><?php echo $this->__("Jewelry")?></a>
										<ul class="primary-sub-menu">
											<li class="diamond-sublist-wrapper">
												
												<div class="container clearfix">
												<!-- <div class="primary-sub-menu-list clearfix">
													<h2 class="sub-arr-icon"><a href="javascript:void(0)"><?php echo $this->__("Store")?></a></h2>
													<ul>
													
													<li><a href="<?php echo $this->geturl("wedding-ring.html")?>"><?php echo $this->__("All Wedding Rings")?></a></li>
													
												</ul>
												</div> -->
												

												
												<div class="secondry-sub-menu-list clearfix">
													<h2><a href="javascript:void(0)"><?php echo $this->__("Earrings")?></a></h2>
													<ul>
											     
								
											       <li><a href="<?php echo $this->geturl("design/settings/index/type/earrings")?>"><?php echo $this->__("Design Your Earrings")?> </a></li>
											       <li><a href="<?php echo $this->geturl("earrings.html")?>"> <?php echo $this->__("All Earrings")?></a></li>
											      
										        </ul>
										        
										        <h2><a href="javascript:void(0)"><?php echo $this->__("Pendants")?></a></h2>
													<ul>
											        <li><a href="<?php echo $this->geturl("design/settings/index/type/pendants")?>"><?php echo $this->__("Design Your Pendants")?></a></li>
											       <li><a href="<?php echo $this->geturl("pendant.html")?>"><?php echo $this->__("All Pendants")?></a></li>											   								       
											      
										        </ul>
										        
										         <h2><a href="javascript:void(0)"><?php echo $this->__("Bracelets")?></a></h2>
													<ul>
											     
											       <li><a href="<?php echo $this->geturl("bracelets1.html")?>"><?php echo $this->__("All Bracelets")?></a></li>
									
											      
										        </ul>
												</div>
										        
										        <div class="third-sub-menu-list">
										        	<h2><?php echo $this->__("Knowledge")?></h2>
										        	<div class="clearfix">
										        		<img src="<?php echo $this->getskinurl("images/") ?>jewelry-sub-list-img.jpg" alt=" " title=" " />
										        		<ul>
										        			<li><a href="<?php echo $this->geturl("knowledge-earing")?>"><?php echo $this->__("Earring Knowledge")?></a></li>
										        			<li><a href="<?php echo $this->geturl("knowledge-necklace")?>"><?php echo $this->__("Pendant Knowledge")?></a></li>
										        			<li><a href="<?php echo $this->geturl("knowledge-bracelet")?>"><?php echo $this->__("Bracelet Knowledge")?></a></li>
										        			

										        		</ul>
										        	</div>
										        </div>
										        
										        </div>
										</li>
										</ul>
									</li>
							
								</ul>
							</nav>