
<?php $_items = $this->getReviewsCollection()->getItems();?>
<?php if (count($_items)):?>
<div class="collateral-box dedicated-review-box" id="customer-reviews">
    <?php echo $this->getChildHtml('toolbar') ?>
    <ol style="margin-top:15px;">
	 <table class="allreview" rules="all" >
           <tbody> 			
		    	<tr>
				<th >Title</th>
				<th >Rating</th>
				<th >Review</th>
				</tr>				
        <?php foreach ($_items as $_review):?>
				<tr>
				<td width="100">
                <strong><?php echo $this->htmlEscape($_review->getTitle()) ?></strong> <?php echo $this->__('Review by %s', $this->htmlEscape($_review->getNickname())) ?>
                </td>
				<td width="150">
				<table class="ratings-list" cellspacing="0">
                    <tbody>
                        <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                        <tr>
                            <td class="label"><strong><?php echo $_vote->getRatingCode() ?></strong></td>
                            <td>
                                <div class="rating-box">
                                    <div class="rating" style="width: <?php echo $_vote->getPercent() ?>%;"></div>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
				</td>	
				<td>
                <p><?php echo nl2br($this->htmlEscape($_review->getDetail())) ?> <?php echo $this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt()), 'long') ?></p>
                 </td>
				 </tr>			  
        <?php endforeach; ?>
		</tbody>
		</table>
    </ol>

    <?php echo $this->getChildHtml('toolbar') ?>
</div>
<?php endif;?>

<br/>
<?php if($this->getflag()==1):?>
<?php  echo $this->getLayout()->createBlock('review/form')->setBlockId('product.review.form')->toHtml() ?> 


<?php endif ?>