<div class="pager css3 row-fluid show-grid">
    <div class="limiter span5" style="float:left; margin-right:28px; " >		
        <?php echo $this->getChildHtml('filter_toolbar_limiter') ?>	
    </div>	
    <div class="sorter span5">		
        <?php //echo $this->getChildHtml('filter_toolbar_sort') ?>	
         <?php echo $this->getPagerHtml(); ?>
    </div>	
</div>
<!--<div class="pager css3 row-fluid show-grid">
    <div class="mode span3">		
        <?php //echo $this->getChildHtml('filter_toolbar_mode') ?>	
    </div>	
    <div class="span3 pageBlock">		
        <?php //echo $this->getPagerHtml(); ?>	
    </div>
</div>-->