
<div class="block block-cart">
    <?php $_cartQty = $this->getSummaryCount() ?>

    <div class="block-content">

    <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>

    <?php endif ?>
    <?php $_items = $this->getRecentItems() ?>
    <?php if(count($_items)): ?>
      
        <ol id="cart-sidebar" class="mini-products-list">
        <?php foreach($_items as $_item): ?>
            <?php echo $this->getItemHtml($_item) ?>
        <?php endforeach; ?>
        </ol>
      <div class="actions">
        <?php echo $this->getChildHtml('extra_actions') ?>
		 <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('購物車')) ?>" class="button" onclick="setLocation('<?php echo $this->geturl("checkout/cart/") ?>')"><span><span><?php echo $this->__('購物車') ?></span></span></button>
        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('結賬')) ?>" class="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('結賬') ?></span></span></button>
   
   </div>
        <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
    <?php endif ?>
	
    </div>
</div>

