                  	<aside class="aside">
                        		<h2>我的主頁	 <i class="toggle-icon"></i></h2>
                        		<ul>
			<?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); ?>
            <?php foreach ($_links as $_link): ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="<?php echo ($_last ? ' last' : '') ?>"><a class="active" href="javascript:void(0)"><?php echo $_link->getLabel() ?></a></li>
                <?php else: ?>
                    <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?> 
                        		</ul>
                        		<div class="top">
								<?php echo $this->getlayout()->createBlock("randombanner/banner")->setname("account")->tohtml()?>

                        		</div>
                        	</aside>

