<?php
    /**
    * Magedelight
    * Copyright (C) 2015 Magedelight <info@magedelight.com>
    *
    * NOTICE OF LICENSE
    *
    * This program is free software: you can redistribute it and/or modify
    * it under the terms of the GNU General Public License as published by
    * the Free Software Foundation, either version 3 of the License, or
    * (at your option) any later version.
    *
    * This program is distributed in the hope that it will be useful,
    * but WITHOUT ANY WARRANTY; without even the implied warranty of
    * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    * GNU General Public License for more details.
    *
    * You should have received a copy of the GNU General Public License
    * along with this program. If not, see http://opensource.org/licenses/gpl-3.0.html.
    *
    * @category MD
    * @package MD_Cybersource
    * @copyright Copyright (c) 2015 Mage Delight (http://www.magedelight.com/)
    * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
    * @author Magedelight <info@magedelight.com>
    */
?>
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php $cardInfoData = true; ?>    
    <?php $cards = $this->getCustomerSavedCards(); ?>
    <?php if(count($cards) > 0): ?>
        <?php $cardInfoData = false; ?>
        <li>
            <label for="<?php echo $_code ?>_subscription_id"><?php echo $this->__("Select From Saved Card") ?></label>
            <div class="input-box">
                <select name="payment[subscription_id]" id="<?php echo $_code ?>_subscription_id" class="required-entry">
                    <?php foreach($cards as $_card): ?>
                        <?php $cardReplaced ="XXXX-". $_card['cc_last4']; ?>
                        <option value="<?php echo Mage::helper('core')->encrypt($_card['subscription_id']); ?>"><?php echo sprintf('%s, %s %s',$cardReplaced,$_card['firstname'],$_card['lastname']) ?></option>
                        <?php endforeach; ?>
                    <option value="new"><?php echo $this->__("Use other card") ?></option>
                </select>
            </div>
        </li>
        <?php endif; ?>
    <li class="<?php echo $_code ?>_new" <?php if(!$cardInfoData): ?>style="display:none;"<?php endif; ?>>
        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
        <div class="input-box" style="clear:left">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="<?php if($cardInfoData): ?>required-entry validate-cybersource-type-select<?php endif; ?>">
                <option value=""><?php echo $this->__('--Please Select--')?></option>
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                    <?php endforeach ?>
            </select>
        </div>
    </li>
    <li class="<?php echo $_code ?>_new" <?php if(!$cardInfoData): ?>style="display:none;"<?php endif; ?>>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" pattern="\d*" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text <?php if($cardInfoData): ?>validate-cccybersource-number validate-cccybersource-type<?php endif; ?>" value="" />
        </div>
    </li>
    <li class="<?php echo $_code ?>_new" <?php if(!$cardInfoData): ?>style="display:none;"<?php endif; ?>>
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month <?php if($cardInfoData): ?>validate-cc-exp required-entry<?php endif ?>">
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year <?php if($cardInfoData): ?>required-entry<?php endif ?>">
                    <?php foreach ($this->getCcYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
        <li id="<?php echo $_code ?>_cc_type_cvv_div">
            <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <input type="text" pattern="\d*" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv validate-cccybersource-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
                </div>
                <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
            </div>
        </li>
        <?php endif; ?>
    <?php
        // We need to be able to identify whether they're a guest or 'registering'...
        $quote	= Mage::getSingleton('checkout/session')->getQuote();
        $items	= array();
        if( $quote && $quote->getId() ) {
            $items	= $quote->getAllItems();
        }
       
    ?>
    <?php if( ( !isset($items[0]) || !$items[0]->isNominal() ) &&  Mage::getModel("md_cybersource/config",array('md_cybersource', Mage::getSingleton('adminhtml/session_quote')->getStoreId()))->getSaveCardOptional()): ?>
        <li class="<?php echo $_code ?>_new" <?php if(Mage::getSingleton('adminhtml/session_quote')->getData('customer_id')==0 || $cardInfoData==false): ?>style="display:none;"<?php endif; ?>>
            <label>&nbsp;</label>
            <input type="checkbox" name="payment[save_card]" id="<?php echo $_code ?>_save_card" value="1" checked="checked" autocomplete="on" />
            <label for="<?php echo $_code ?>_save_card" style="float:none;font-weight:normal;"><?php echo $this->__('Save this credit card for future use.'); ?></label>
        </li>
        <?php elseif( ( isset($items[0]) && $items[0]->isNominal() )): ?>
        <li class="<?php echo $_code ?>_new" <?php if(!$cardInfoData): ?>style="display:none;"<?php endif; ?>>
            <input type="hidden" name="payment[save_card]" id="<?php echo $_code ?>_save_card" value="1" /> 
            <?php echo $this->__('<strong>Note:</strong> For your convenience, this card will be stored securely via Cybersource.'); ?>
        </li>
        <?php else: ?>
        <li class="<?php echo $_code ?>_new" <?php if(!$cardInfoData): ?>style="display:none;"<?php endif; ?>>
        <input type="hidden" name="payment[save_card]" id="<?php echo $_code ?>_save_card" value="1" />
    </li>
    <?php endif; ?>
</ul>
<?php if(count($cards) > 0): ?>
    <script type="text/javascript">
        $('<?php echo $_code ?>_subscription_id').observe("change",function(event){
            var sourceElement = Event.findElement(event);
            var currentValue = $(sourceElement).getValue();
            var cVVElement = $('<?php echo $_code ?>_cc_cid');   
             if(currentValue == 'new'){
                  $('<?php echo $_code ?>_cc_type').addClassName('validate-cybersource-type-select');
                  $('<?php echo $_code ?>_cc_type').addClassName('required-entry');
                  $('<?php echo $_code ?>_cc_number').addClassName('validate-cccybersource-number');
                  $('<?php echo $_code ?>_cc_number').addClassName('validate-cccybersource-type');
                  $('<?php echo $_code ?>_expiration').addClassName('validate-cc-exp');
                  $('<?php echo $_code ?>_expiration').addClassName('required-entry');
                  $('<?php echo $_code ?>_expiration_yr').addClassName('required-entry');
               }
               else{
                   $('<?php echo $_code ?>_cc_type').removeClassName('validate-cybersource-type-select');
                  $('<?php echo $_code ?>_cc_type').removeClassName('required-entry');
                  $('<?php echo $_code ?>_cc_number').removeClassName('validate-cccybersource-number');
                  $('<?php echo $_code ?>_cc_number').removeClassName('validate-cccybersource-type');
                  $('<?php echo $_code ?>_expiration').removeClassName('validate-cc-exp');
                  $('<?php echo $_code ?>_expiration').removeClassName('required-entry');
                  $('<?php echo $_code ?>_expiration_yr').removeClassName('required-entry');
                   
               }
                        
            $$(".<?php echo $_code ?>_new").each(function(newCardData){
                 
                if(currentValue == 'new'){
                    $(newCardData).show();
                }else{
                    $(newCardData).hide();

                }
            }); 
            if(cVVElement){
                cVVElement.show();
                if(currentValue == 'new'){
                    cVVElement.addClassName('validate-cccybersource-cvn');
                }else{
                    cVVElement.removeClassName('validate-cccybersource-cvn');
                }
            }
        });
    </script>
    <?php endif; ?>
